.TH SX4 1 "Jul 2023" "sx4 v0.1.0"
.SH NAME
sx4 - Minimal X11 selection tool
.SH SYNOPSIS
sx4
.RB [ \-Bkhv ]
.RB [ \-b
.IR width ]
.RB [ \-c
.IR color ]
.RB [ \-f
.IR format\-string ]
.RB [ \-w
.IR window\-id ]

.SH DESCRIPTION
.B sx4
is a minimal X11 selection tool.
After a successful selection the selected area's dimension will be
printed to standard out (stdout) in the following format:
.BR "x,y,w,h" .

.SH OPTIONS
.TP
.BR "-B, --keep-border"
Include the selected window's border in the selection.
.TP
.BI "-b, --border-width " "width"
Width of the selection border, must be within [0, 512].
.TP
.BI "-c, --color " "<colorname|#hexcolor>"
Color of the selection border.
.TP
.BI "-f, --format " "format\-string"
Change the default output format.
See FORMAT section for more details.
.TP
.BR "-k, --no-keyboard"
Disable keyboard.
.TP
.BI "-w, --window " "window-id"
ID of the window to select.
.TP
.BR "-h, --help"
Show usage and exit.
.TP
.BR "-v, --version"
Show version and exit.

.SH BINDINGS
.TP
.BR "Button1" , " Space"
Start and end the selection.
.TP
.B "Button3"
If no selection is active, select the window under the cursor.
.TP
.BR "Button4" , " Button5" , " f"
If selection is active, swaps the pointer position.
This allows for re-adjusting the selection's starting point.
.TP
.BR "ESC" , " q"
Abort the selection.
.P
While selection is active pressing any mouse button, other than
.IR "Button1" , " Button4 " and " Button5"
will also abort the selection.
.TP
.BR ArrowLeft ", " ArrowRight ", " ArrowUp ", " ArrowDown ", " h ", " j ", " k ", " l
Moves the cursor by 16 pixels.
.B Control
modifier can be used to move by 1 pixel.
.B Shift
modifier can be used to move in bigger increments of 128 pixels.

.SH FORMAT
The output format can be customized via the \-f flag.
The format\-string accepts specifiers that are expanded before outputting.
The following specifiers are supported:
.TP
.B "%x"
x co\-ordinate.
.TP
.B "%y"
y co\-ordinate.
.TP
.B "%w"
width.
.TP
.B "%h"
height.
.TP
.B "%W"
absolute co\-ordinate of the width.
.TP
.B "%H"
absolute co\-ordinate of the height.
.TP
.B "%n"
a new-line.
.TP
.B "%%"
a literal percent\-sign.
.P
For example "%x,%y,%w,%h%n" would be equivalent to the default output format.

.SH AUTHORS
NRK <nrk@disroot.org>

.SH BUGS
.SS "Reporting Bugs"
For reporting bugs, either open an issue under the Codeberg repo
<https://codeberg.org/NRK/sx4> or send an email to <nrk@disroot.org>.
